# Generated by Django 3.2.8 on 2021-11-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityindicator',
            name='question11',
            field=models.IntegerField(choices=[(1, 'YES'), (-1, 'NO'), (0, 'Unknown'), (2, 'Non Applicable')]),
        ),
        migrations.AlterField(
            model_name='securityindicator',
            name='question12',
            field=models.IntegerField(choices=[(1, 'YES'), (-1, 'NO'), (0, 'Unknown'), (2, 'Non Applicable')]),
        ),
        migrations.AlterField(
            model_name='securityindicator',
            name='question13',
            field=models.IntegerField(choices=[(1, 'YES'), (-1, 'NO'), (0, 'Unknown'), (2, 'Non Applicable')]),
        ),
        migrations.AlterField(
            model_name='securityindicator',
            name='question14',
            field=models.IntegerField(choices=[(1, 'YES'), (-1, 'NO'), (0, 'Unknown'), (2, 'Non Applicable')]),
        ),
        migrations.AlterField(
            model_name='securityindicator',
            name='question15',
            field=models.IntegerField(choices=[(1, 'YES'), (-1, 'NO'), (0, 'Unknown'), (2, 'Non Applicable')]),
        ),
        migrations.AlterField(
            model_name='securityindicator',
            name='question16',
            field=models.IntegerField(choices=[(1, 'YES'), (-1, 'NO'), (0, 'Unknown'), (2, 'Non Applicable')]),
        ),
        migrations.AlterField(
            model_name='securityindicator',
            name='question17',
            field=models.IntegerField(choices=[(1, 'YES'), (-1, 'NO'), (0, 'Unknown'), (2, 'Non Applicable')]),
        ),
        migrations.AlterField(
            model_name='securityindicator',
            name='question18',
            field=models.IntegerField(choices=[(1, 'YES'), (-1, 'NO'), (0, 'Unknown'), (2, 'Non Applicable')]),
        ),
        migrations.AlterField(
            model_name='securityindicator',
            name='question19',
            field=models.IntegerField(choices=[(1, 'YES'), (-1, 'NO'), (0, 'Unknown'), (2, 'Non Applicable')]),
        ),
        migrations.AlterField(
            model_name='securityindicator',
            name='question20',
            field=models.IntegerField(choices=[(1, 'YES'), (-1, 'NO'), (0, 'Unknown'), (2, 'Non Applicable')]),
        ),
        migrations.AlterField(
            model_name='securityindicator',
            name='question21',
            field=models.IntegerField(choices=[(1, 'YES'), (-1, 'NO'), (0, 'Unknown'), (2, 'Non Applicable')]),
        ),
        migrations.AlterField(
            model_name='securityindicator',
            name='question22',
            field=models.IntegerField(choices=[(1, 'YES'), (-1, 'NO'), (0, 'Unknown'), (2, 'Non Applicable')]),
        ),
        migrations.AlterField(
            model_name='securityindicator',
            name='question23',
            field=models.IntegerField(choices=[(1, 'YES'), (-1, 'NO'), (0, 'Unknown'), (2, 'Non Applicable')]),
        ),
    ]
