# Generated by Django 3.2.8 on 2021-12-08 07:38

from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211116_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.data')),
                ('completeness', models.IntegerField(default=0)),
                ('accuracy', models.JSONField()),
                ('gain_ratio', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='attribute_data',
            field=models.FileField(upload_to='attribute/', validators=[mainapp.models.file_size, mainapp.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='data',
            name='rawdata',
            field=models.FileField(upload_to='rawdata/', validators=[mainapp.models.file_size, mainapp.models.validate_file_extension]),
        ),
    ]
