# Generated by Django 3.2.8 on 2021-12-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211208_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='accuracy',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='gain_ratio',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
