# Generated by Django 3.2.8 on 2021-12-17 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211208_0755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicator',
            old_name='gain_ratio',
            new_name='info_content',
        ),
    ]
