# Generated by Django 3.2.8 on 2021-12-22 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0005_rename_gain_ratio_indicator_info_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighFrequencyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Data Name')),
                ('rawdata', models.FileField(upload_to='HFD/rawdata/', validators=[mainapp.models.validate_file_extension])),
                ('config', models.FileField(upload_to='HFD/config/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transData', models.ManyToManyField(blank=True, null=True, to='mainapp.Data')),
            ],
        ),
    ]
