# Generated by Django 3.2.8 on 2021-12-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_highfrequencydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highfrequencydata',
            name='transData',
            field=models.ManyToManyField(blank=True, to='mainapp.Data'),
        ),
    ]
