# Generated by Django 3.2.8 on 2022-01-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_highfrequencydata_transdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='freq_config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
