# Generated by Django 3.2.8 on 2021-12-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211104_0751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Security',
        ),
    ]
